config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  get 'manager/index'
  get 'manager/guests'

  resources :guests
  resources :sessions, only: [:new, :create, :destroy, :index]

  #get 'static_page/index'
  get '/cerimonia'        =>  'static_page#ceremony',       :as =>  :ceremony
  get '/listaPresentes'   =>  'static_page#gift_list',      :as =>  :gift_list
  get '/depoimentos'      =>  'static_page#testimonials',   :as =>  :testimonials
  get '/historiaCasal'    =>  'static_page#couple_history', :as =>  :couple_history
  get '/fornecedores'     =>  'static_page#suppliers',      :as =>  :suppliers
  get '/pessoasEspeciais' =>  'static_page#main_people',    :as =>  :main_people
  get '/gerenciamento'    =>  'manager#index',              :as =>  :manager

  match '/savarDepoimentos'       =>  'static_page#create_testimonial',       via: 'post',          :as =>  :save_testimonials
  match '/acesso'                 =>  'sessions#new',                         via:  'get',          :as =>  :login
  match '/upload'                 =>  'manager#guests',                       via:  'post',         :as =>  :upload
  match '/textoNossaHistoria'     =>  'manager#save_couple_history_content',  via:  %w(PATCH post), :as =>  :save_couple_history_content
  # match '/textoNossasPais'        =>  'manager#save_parents_history_content', via:  %w(PATCH post), :as =>  :save_main_people_content
  match '/textoNossasPais'        =>  'manager#save_main_people_content',     via:  %w(PATCH post), :as =>  :save_main_people_content
  match '/sair'                   =>  'sessions#destroy',                     via:  'delete',       :as =>  :signout
  # match '/confirmar'              =>  'guests#confirm',                       via:  %w(get post),   :as =>  :confirmation
  match '/guestAutocompleteList'  =>  'guests#guest_autocomplete_list',       via:  %w(get post)
  match '/selectGuest'            =>  'guests#select_guest',                  via:  %w(get post)
  match '/confirmThisGuest'       =>  'guests#confirm_this_guest',            via:  'post'

  root 'static_page#index'
end

app/controllers/manager_controller.rb
class ManagerController < ApplicationController
  before_action :go_to_login_if_needed

  WORDS_TO_BE_EXCLUDED = ['pe ', 'irmã ', 'tia ', 'tio ', 'vó ']

  def index
    $couple_history = ContentText.where(:page => 'couple_history').first
    $couple_history = create_if_needed($couple_history, 'couple_history')

    $parents_history = ContentText.where(:page => 'parent_history').first
    $parents_history = create_if_needed($parents_history, 'parent_history')

    $adriano_history = ContentText.where(:page => 'adriano_history').first
    $adriano_history = create_if_needed($adriano_history, 'adriano_history')

    $ana_claudia_history = ContentText.where(:page => 'ana_claudia_history').first
    $ana_claudia_history = create_if_needed($ana_claudia_history, 'ana_claudia_history')

    $carlos_history = ContentText.where(:page => 'carlos_history').first
    $carlos_history = create_if_needed($carlos_history, 'carlos_history')

    $cleiton_history = ContentText.where(:page => 'cleiton_history').first
    $cleiton_history = create_if_needed($cleiton_history, 'cleiton_history')

    $diogo_history = ContentText.where(:page => 'diogo_history').first
    $diogo_history = create_if_needed($diogo_history, 'diogo_history')

    $isabel_history = ContentText.where(:page => 'isabel_history').first
    $isabel_history = create_if_needed($isabel_history, 'isabel_history')

    $isa_edi_history = ContentText.where(:page => 'isa_edi_history').first
    $isa_edi_history = create_if_needed($isa_edi_history, 'isa_edi_history')

    $isis_history = ContentText.where(:page => 'isis_history').first
    $isis_history = create_if_needed($isis_history, 'isis_history')

    $jana_al_history = ContentText.where(:page => 'jana_al_history').first
    $jana_al_history = create_if_needed($jana_al_history, 'jana_al_history')

    $maiara_history = ContentText.where(:page => 'maiara_history').first
    $maiara_history = create_if_needed($maiara_history, 'maiara_history')

    $maria_history = ContentText.where(:page => 'maria_history').first
    $maria_history = create_if_needed($maria_history, 'maria_history')

    $murilo_history = ContentText.where(:page => 'murilo_history').first
    $murilo_history = create_if_needed($murilo_history, 'murilo_history')

    $pe_milton_history = ContentText.where(:page => 'pe_milton_history').first
    $pe_milton_history = create_if_needed($pe_milton_history, 'pe_milton_history')

    $rahira_history = ContentText.where(:page => 'rahira_history').first
    $rahira_history = create_if_needed($rahira_history, 'rahira_history')

    $antonio_history = ContentText.where(:page => 'antonio_history').first
    $antonio_history = create_if_needed($antonio_history, 'antonio_history')

    $maria_luiza_history = ContentText.where(:page => 'maria_luiza_history').first
    $maria_luiza_history = create_if_needed($maria_luiza_history, 'maria_luiza_history')

    $sobrinhos_history = ContentText.where(:page => 'sobrinhos_history').first
    $sobrinhos_history = create_if_needed($sobrinhos_history, 'sobrinhos_history')

    $raquel_history = ContentText.where(:page => 'raquel_history').first
    $raquel_history = create_if_needed($raquel_history, 'raquel_history')

    $users_list = AccessUsers.all
  end

  def save_couple_history_content
    ContentText.delete_all(:page => 'couple_history')
    @couple_history = ContentText.new(content_texts_params)
    if @couple_history.save
      redirect_to couple_history_path
    end
  end

  # def save_parents_history_content
  def save_main_people_content
    # ContentText.delete_all(:page => 'parent_history')
    ContentText.delete_all(:page => content_texts_params[:page])
    @new_content = ContentText.new(content_texts_params)
    if @new_content.save
      redirect_to main_people_path
    end
  end

  def guests
    saved_file = uploadFile(params[:upload])
    doc = SimpleXlsxReader.open saved_file
    worksheet = doc.sheets[0]
    Guests.delete_all
    ActiveRecord::Base.transaction do
      worksheet.rows.each_with_index do |line_val, idx|
        break if line_val.all? { |x| x == nil }
        next if idx == 0  
        new_guest = Guests.new
        new_guest.name = normalize_name(line_val[0])
        new_guest.accompanying_number = line_val[2]
        new_guest.save
      end
    end
    redirect_to guests_index_path
  end

  private
    def go_to_login_if_needed
      redirect_to login_path unless logged_in?
    end

    def content_texts_params
      params.require(:content_text).permit(:page, :title, :page_text)
    end

    def uploadFile(upload)
      name =  upload['datafile'].original_filename
      directory = 'public/uploaded/temp'
      # delete all files or directoris from temp folder
      delete_existing_files(directory)
      # create the file path
      path = File.join(directory, name)
      # write the file
      File.open(path, 'wb') { |f| f.write(upload['datafile'].read) }

      path
    end

    def delete_existing_files(dir_path)
      Pathname.new(dir_path).children.each { |p| p.unlink }
    end

    def normalize_name(name)
      aux = nil
      normalized_name = ''
      name = name.gsub(',', ' e ')

      WORDS_TO_BE_EXCLUDED.each do |word|
        unless name.downcase.index(word).nil?
          aux = name.downcase.gsub(word, '').split(' ')
        end
      end

      aux = name.split(' ') if aux.blank?
      aux.each { |n| normalized_name += n.size > 2 ? n.capitalize + ' ' : n + ' ' }

      return normalized_name[0...-1]
    end

    def create_if_needed(obj, page_type)
      if obj.nil?
        obj = ContentText.new
        obj[:page] = page_type
      end
      obj
    end
end

app/helpers/manager_helper.rb
module ManagerHelper
end

app/views/manager/_couple_history_manager.html.erb
<style>
  label {
    font-weight: bold;
  }
  #content_text_title {
    border: 1px solid #b6b6b6;
    margin-bottom: 20px;
    background: #fff;
  }
</style>

<%= form_for content, url: save_couple_history_content_path do |f| %>
  <%= f.label :Título %>
  <%= f.text_field :title %>
  <%= f.hidden_field :page, :value => content[:page] %>
  <%= f.label :page_text, 'Conte a história do casal' %>
  <%= f.cktext_area :page_text, :ckeditor => {:language => 'pt'} %>
<% end %>

app/views/manager/_guests_mnager.html.erb
<span class="icon-arrow-right left" style="display: inline-block; margin: 5px 0 0 0;"></span><h5 style="margin: 0 0 0 6px; display: inline-block;"><%= link_to 'Gerenciar convidados já importados.', guests_index_path %></h5>
<br /><br />
<span class="icon-arrow-right left" style="display: inline-block margin: 5px 0 0 0;"></span><h5 style="margin: 0 0 0 6px; color: #000; display: inline-block">Importar lista de convidados (CUIDADO!!! Esta ação apagará todos os convidados atuais caso existam.)</h5>
<br />
<%= form_tag(upload_path, :multipart => true, :style => 'margin: 8px 15px 0 21px;') do %>
    <p style="text-align: left;">
        <label for="upload_file">Arquivo com a lista</label> :
        <%= file_field 'upload', 'datafile', :style => 'width: 550px; background: #fff;' %>
    </p>
    <%= submit_tag 'Upload', :class => 'bnt-apparence right', :style => 'margin-bottom: 20px;' %>
<% end %>

app/views/manager/_users_manager.html.erb
<style>
  h1 {
    color: #fff;
  }
  table {
    width: 100%;
    margin: 0 auto;
    border-collapse: collapse;
    border: 0;
    text-align: center;
  }
  th {
    padding: 6px 8px;
    background: #FEA841;
    color: #fff;
    border-bottom: 3px solid #FEA841;
    font-size: 15px;
  }
  td:first-child {
    text-align: left;
  }
  td {
    padding: 6px  8px;
    border-bottom: 1px solid #FEA841;
  }
  table a {
    color: #fff;
  }
</style>

<div class="clearfix" style="width: 100%; display: table;">
  <div style="display: table-cell; width: 40%;">lerolrero</div>
  <div style="display: table-cell; width: 60%;">
    <h3 style="color: #000;">► Usuários atuais</h3>

    <table>
      <thead>
        <tr>
          <th>Nome</th>
          <th>Data de criação</th>
          <th>Última edição no usuário</th>
        </tr>
        </thead>

        <tbody>
          <% Array.wrap(users).each do |u| %>
            <tr>
              <td><%= u.name %></td>
              <td><%= u.created_at %></td>
              <td><%= u.updated_at %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <%= link_to 'Criar convidado', new_guests_path, :class => 'bnt-apparence', :style => 'margin-top: 30px;' %>
  </div>
</div>

app/views/manager/guests.html.erb
<h1>Manager#guests</h1>
<p>Find me in app/views/manager/guests.html.erb</p>

app/views/manager/index.html.erb
<% @godparents = Hash.new %>
<% @couple_history = $couple_history if $couple_history %>
<% @parents_history = $parents_history if $parents_history %>
<% @godparents[:adriano_hist] = $adriano_history if $adriano_history %>
<% @godparents[:ana_claudia_hist] = $ana_claudia_history if $ana_claudia_history %>
<% @godparents[:carlos_hist] = $carlos_history if $carlos_history %>
<% @godparents[:cleiton_hist] = $cleiton_history if $cleiton_history %>
<% @godparents[:diogo_hist] = $diogo_history if $diogo_history %>
<% @godparents[:isabel_hist] = $isabel_history if $isabel_history %>
<% @godparents[:isa_edi_hist] = $isa_edi_history if $isa_edi_history %>
<% @godparents[:isis_hist] = $isis_history if $isis_history %>
<% @godparents[:jana_al_hist] = $jana_al_history if $jana_al_history %>
<% @godparents[:maiara_hist] = $maiara_history if $maiara_history %>
<% @godparents[:maria_hist] = $maria_history if $maria_history %>
<% @godparents[:murilo_hist] = $murilo_history if $murilo_history %>
<% @godparents[:pe_milton_hist] = $pe_milton_history if $pe_milton_history %>
<% @godparents[:rahira_hist] = $rahira_history if $rahira_history %>
<% @godparents[:antonio_hist] = $antonio_history if $antonio_history %>
<% @godparents[:maria_luiza_hist] = $maria_luiza_history if $maria_luiza_history %>
<% @godparents[:sobrinhos_hist] = $sobrinhos_history if $sobrinhos_history %>
<% @godparents[:raquel_hist] = $raquel_history if $raquel_history %>
<% @users_list = $users_list if $users_list %>
<div class="container" style="width: 80%; height: 75%;  background: rgba(68, 68, 68, .4);">
  <div class="tabContainer">
    <!-- Labels -->
    <div id="managerTabOne" class="tabLabel selected">História do casal</div>
    <div id="managerTabTwo" class="tabLabel">Gerenciar convidados</div>
    <div id="managerTabThree" class="tabLabel">Gerenciar texto dos pais, padrinhos e das crianças</div>
    <div id="managerTabFour" class="tabLabel">Gerenciamento de usuários administradores</div>

    <!-- Labels containers -->
    <div class="tabLabelContainer managerTabOne clearfix selected">
      <%= render partial: 'manager/couple_history_manager', locals: { :content => @couple_history } %>
    </div>
    <div class="tabLabelContainer managerTabTwo clearfix">
      <%= render partial: 'manager/guests_mnager' %>
    </div>
    <div class="tabLabelContainer managerTabThree clearfix">
      <%= render partial: 'common/main_people_screen', locals: { :is_editable => true, :parents => @parents_history, :godparents_list => @godparents } %>
    </div>
    <div class="tabLabelContainer managerTabFour clearfix">
      <%= render partial: 'manager/users_manager', locals: { :users => @users_list} %>
    </div>
  </div>
</div>