config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  get 'manager/index'
  get 'manager/guests'

  resources :guests
  resources :sessions, only: [:new, :create, :destroy, :index]

  #get 'static_page/index'
  get '/cerimonia'        =>  'static_page#ceremony',       :as =>  :ceremony
  get '/listaPresentes'   =>  'static_page#gift_list',      :as =>  :gift_list
  get '/depoimentos'      =>  'static_page#testimonials',   :as =>  :testimonials
  get '/historiaCasal'    =>  'static_page#couple_history', :as =>  :couple_history
  get '/fornecedores'     =>  'static_page#suppliers',      :as =>  :suppliers
  get '/pessoasEspeciais' =>  'static_page#main_people',    :as =>  :main_people
  get '/gerenciamento'    =>  'manager#index',              :as =>  :manager

  match '/savarDepoimentos'       =>  'static_page#create_testimonial',       via: 'post',          :as =>  :save_testimonials
  match '/acesso'                 =>  'sessions#new',                         via:  'get',          :as =>  :login
  match '/upload'                 =>  'manager#guests',                       via:  'post',         :as =>  :upload
  match '/textoNossaHistoria'     =>  'manager#save_couple_history_content',  via:  %w(PATCH post), :as =>  :save_couple_history_content
  # match '/textoNossasPais'        =>  'manager#save_parents_history_content', via:  %w(PATCH post), :as =>  :save_main_people_content
  match '/textoNossasPais'        =>  'manager#save_main_people_content',     via:  %w(PATCH post), :as =>  :save_main_people_content
  match '/sair'                   =>  'sessions#destroy',                     via:  'delete',       :as =>  :signout
  # match '/confirmar'              =>  'guests#confirm',                       via:  %w(get post),   :as =>  :confirmation
  match '/guestAutocompleteList'  =>  'guests#guest_autocomplete_list',       via:  %w(get post)
  match '/selectGuest'            =>  'guests#select_guest',                  via:  %w(get post)
  match '/confirmThisGuest'       =>  'guests#confirm_this_guest',            via:  'post'

  root 'static_page#index'
end

app/models/guests.rb
class Guests < ActiveRecord::Base
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  before_action :set_guest, only: [:show, :edit, :update, :destroy]
  before_action :go_to_login_if_needed, except: [:confirm, :guest_autocomplete_list, :select_guest, :confirm_this_guest]

  # GET /guests
  # GET /guests.json
  def index
    @guests = Guests.all
  end

  # GET /guests/1
  # GET /guests/1.json
  def show
  end

  # GET /guests/new
  def new
    @guest = Guests.new
  end

  # GET /guests/1/edit
  def edit
  end

  # POST /guests
  # POST /guests.json
  def create
    @guest = Guests.new(guest_params)

    respond_to do |format|
      if @guest.save
        format.html { redirect_to @guest, notice: 'Guests was successfully created.' }
        format.json { render :show, status: :created, location: @guest }
      else
        format.html { render :new }
        format.json { render json: @guest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /guests/1
  # PATCH/PUT /guests/1.json
  def update
    respond_to do |format|
      if @guest.update(guest_params)
        format.html { redirect_to @guest, notice: 'Guests was successfully updated.' }
        format.json { render :show, status: :ok, location: @guest }
      else
        format.html { render :edit }
        format.json { render json: @guest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /guests/1
  # DELETE /guests/1.json
  def destroy
    @guest.destroy
    respond_to do |format|
      format.html { redirect_to guests_url, notice: 'Guests was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def confirm
  end

  def guest_autocomplete_list
    render :text => '' and return if params[:data].blank?
    # data = Guests.select('distinct name').where("upper(name) like '#{params[:data].upcase}%'").limit(10).all
    @guests = Guests.where("upper(name) like '%#{params[:data].upcase}%'").order('name').all
    str = ''
    # Array.wrap(data).each do |option|
    Array.wrap(@guests).each do |option|
      str += "#{option['name']}|"
    end
    str += ''
    render :text => str
  end

  def select_guest
    guest_name = removeRepetition(params[:data].gsub(/[^a-zA-Z\s]/, '%'))
    @guest_to_confirm = Guests.where("upper(name) like '#{guest_name.upcase}%'").first

    render :json => @guest_to_confirm
  end

  def confirm_this_guest
    guest = Guests.find(params[:data])
    if guest.is_confirmed
      render :text => 'Sua presença já foi confirmada!'
    else
      guest.is_confirmed = true
      guest.save
      render :text => 'Salvo'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_guest
      @guest = Guests.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def guest_params
      params.require(:guests).permit(:name, :accompanying_number)
    end

    def go_to_login_if_needed
      redirect_to login_path unless logged_in?
    end

    def removeRepetition(arr)
      result = ''
      for i in 0...arr.size
        next if i != 0 && arr[i] == arr[i - 1] && arr[i] == '%'
        result += arr[i]
      end
      return result
    end
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/views/guests/_form.html.erb
<%= form_for(@guest) do |f| %>
  <% if @guest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@guest.errors.count, "error") %> prohibited this guest from being saved:</h2>

      <ul>
      <% @guest.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :número_de_acompanhantes %><br>
    <%= f.number_field :accompanying_number, :style => 'width: 100%;' %>
  </div>
    <div class="field">
        <%= f.check_box :is_confirmed %>
        <%= f.label :confirmado, :confirmado, :style => 'position: absolute;' %><br>
    </div>
  <div class="actions clearfix">
    <%= f.submit 'Salvar', :class => 'bnt-apparence' %>
  </div>
  <br />
<% end %>

app/views/guests/confirm.html.erb
<style>
  section, section a {
    color: #fff;
  }
  strong {
    font-weight: bolder;
  }
  #guests {
    float: left;
    display: inline-block;
    width: 71%;
    height: 47px;
  }
  #find_guest {
      padding: 12px 20px !important;
  }
  #btn_confirm {
      margin-top: 15px;
      padding: 12px 20px !important;
  }
</style>
<section id="login-area" class="centered">
  <article>
    <div id="fields-area" class="clearfix">
      <h4 class="hideGuest" style="color: #fff; margin: 0 0 15px 0; border-bottom: 3px solid #FEA841;">► Para confirmar sua presença escreva seu nome na caixa abaixo:</h4>
        <div class="clearfix hideGuest" style="width: 100%; padding: 0 0 20px 0;">
          <%= form_tag do %>
            <%= label_tag(:nome, 'Insira seu nome: ') %>
            <div style="width: 100%;">
              <%= text_field_tag(:guests, nil, :list => 'guests_list') %>
              <%= link_to 'Buscar', '#', :id => 'find_guest', :class => 'bnt-apparence' %>
            </div>
            <datalist id="guests_list">
            </datalist>
          <% end %>
        </div>

        <div id="confirm_presence" class="clearfix" style="display: none; width: 100%; margin: 12px 0 0 0;">
          <h4 style="color: #fff; text-align: justify; border-bottom: 3px solid #FEA841;">► Se os dados abaixo estiverem corretos confirme sua presença.</h4>
          <%= form_tag do %>
            <%= label_tag(:nome, 'Nome: ') %><br />
            <%= text_field_tag(:name, nil, :disabled => true) %><br />
            <%= label_tag(:accompanying_number, 'N° de Convites (Você mais acompanhantes): ') %><br />
            <%= text_field_tag(:accompanying_number, nil, :disabled => true) %><br />
            <%= hidden_field_tag :guest_id, :value => session[:user_id]%>
            <%= link_to 'Confirmar presença', '#', :id => 'btn_confirm', :class => 'bnt-apparence' %>
          <% end %>
        </div>

        <div id="confirm_msg" class="clearfix" style="display: none; width: 100%;">
            <%= image_tag(image_url('noiva.png'), width: '50', height: '47', style: 'float: left;') %>
          <h4 style="display: inline-block; width: 300px; margin: 7px 0 0 10px; text-align: justify; color: #fff;">
            Sua presença foi confirmada com sucesso. Fico feliz em poder contar com sua presença!
          </h4>
        </div>
      </div>
  </article>
</section>

app/views/guests/edit.html.erb
<style>
  section, section a {
    color: #fff;
  }
  strong {
    font-weight: bolder;
  }
</style>

<section id="login-area" class="centered">
  <div id="fields-area">
    <h2 style="color: #fff; margin: 0 0 15px 0; border-bottom: 3px solid #FEA841;">► Editar convidado</h2>

    <%= render 'form' %>

    <div class="right" style="margin-bottom: 20px;">
      <%= link_to 'Detalhes', @guest %> |
      <%= link_to 'Voltar', guests_index_path %>
    </div>
    <br />
  </div>
</section>

app/views/guests/index.html.erb
<style>
  h1 {
    color: #fff;
  }
  table {
    width: 100%;
    margin: 0 auto;
    border-collapse: collapse;
    border: 0;
    text-align: center;
  }
  th {
    padding: 6px 8px;
    background: #FEA841;
    color: #fff;
    border-bottom: 3px solid #FEA841;
    font-size: 15px;
  }
  td:first-child {
    text-align: left;
  }
  td {
    padding: 6px  8px;
    border-bottom: 1px solid #FEA841;
  }
  table a {
    color: #fff;
  }
</style>

<div class="container clearfix">
  <h1>► Lista de convidados</h1>

  <table>
    <thead>
      <tr>
        <th>Nome</th>
        <th>N° Acompanhantes</th>
        <th>Confirmado</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
    <% @guests.each do |guest| %>
      <tr>
        <td><%= guest.name %></td>
        <td><%= guest.accompanying_number %></td>
        <td><%= guest.is_confirmed ? 'Sim' : 'Não' %></td>
        <td><%= link_to 'Detalhes', guest %></td>
        <td><%= link_to 'Editar', edit_guests_path(guest) %></td>
        <td><%= link_to 'Deletar', guest, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
  <br>

  <%= link_to 'Criar convidado', new_guests_path, :class => 'bnt-apparence' %>
</div>

app/views/guests/new.html.erb
<h1>New guest</h1>

<%= render 'form' %>

<%= link_to 'Back', guests_index_path %>

app/views/guests/show.html.erb
<style>
  section, section a {
    color: #fff;
  }
  strong {
    font-weight: bolder;
  }
</style>

<section id="login-area" class="centered">
  <div id="fields-area">
    <h2 style="color: #fff; margin: 0; border-bottom: 3px solid #FEA841;">► Detalhe do convidado</h2>
    <p id="notice"><%= notice %></p>

    <p>
      <strong>Nome:</strong>
      <%= @guest.name %>
    </p>
    <p>
      <strong>Número de acompanhantes:</strong>
      <%= @guest.accompanying_number %>
    </p>
    <p>
      <%= check_box_tag('Confirmado', @guest.is_confirmed, @guest.is_confirmed, :disabled => true) %>
      <strong style="position: absolute;">Confirmado</strong>
    </p>

    <div class="right" style="margin-bottom: 20px;">
      <%= link_to 'Editar', edit_guests_path(@guest) %> |
      <%= link_to 'Voltar', guests_index_path %>
    </div>
    <br />
  </div>
</section>