config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  get 'manager/index'
  get 'manager/guests'

  resources :guests
  resources :sessions, only: [:new, :create, :destroy, :index]

  #get 'static_page/index'
  get '/cerimonia'        =>  'static_page#ceremony',       :as =>  :ceremony
  get '/listaPresentes'   =>  'static_page#gift_list',      :as =>  :gift_list
  get '/depoimentos'      =>  'static_page#testimonials',   :as =>  :testimonials
  get '/historiaCasal'    =>  'static_page#couple_history', :as =>  :couple_history
  get '/fornecedores'     =>  'static_page#suppliers',      :as =>  :suppliers
  get '/pessoasEspeciais' =>  'static_page#main_people',    :as =>  :main_people
  get '/gerenciamento'    =>  'manager#index',              :as =>  :manager

  match '/savarDepoimentos'       =>  'static_page#create_testimonial',       via: 'post',          :as =>  :save_testimonials
  match '/acesso'                 =>  'sessions#new',                         via:  'get',          :as =>  :login
  match '/upload'                 =>  'manager#guests',                       via:  'post',         :as =>  :upload
  match '/textoNossaHistoria'     =>  'manager#save_couple_history_content',  via:  %w(PATCH post), :as =>  :save_couple_history_content
  # match '/textoNossasPais'        =>  'manager#save_parents_history_content', via:  %w(PATCH post), :as =>  :save_main_people_content
  match '/textoNossasPais'        =>  'manager#save_main_people_content',     via:  %w(PATCH post), :as =>  :save_main_people_content
  match '/sair'                   =>  'sessions#destroy',                     via:  'delete',       :as =>  :signout
  # match '/confirmar'              =>  'guests#confirm',                       via:  %w(get post),   :as =>  :confirmation
  match '/guestAutocompleteList'  =>  'guests#guest_autocomplete_list',       via:  %w(get post)
  match '/selectGuest'            =>  'guests#select_guest',                  via:  %w(get post)
  match '/confirmThisGuest'       =>  'guests#confirm_this_guest',            via:  'post'

  root 'static_page#index'
end

app/views/common/_lightbox.html.erb
<section id="lightbox">
  <header>
    <span id="title">Deixe uma mensagem para os noivos!</span>
    <span class="icon-close right" />
  </header>
  <section class="content clearfix">
    <%= form_for testimonial, url: save_testimonials_path do |t| %>
      <%= t.label 'Seu nome:' %> <br />
      <%= t.text_field :name %> <br />
      <%= t.label 'Depoimento:' %> <br />
      <%= t.text_area :testimonial %> <br /> <br />
      <%= t.button 'Ok', id: 'loginPost', class: 'right' %>
    <% end %>
  </section>
</section>
<section id="fade" class="overlay_content"></section>

app/views/common/_main_people_screen.html.erb
<% is_editable ||= false %>
<% parents ||= nil %>
<% godparents_list ||= nil %>

<div class="accordionContainer">
  <div id="accordionOne" class="accordionLabel selected"><span class="icon-arrow-right left" style="display: inline-block; margin: 3px 5px 0 0;"></span> Família dos Noivos</div>
  <div class="accordionLabelContainer accordionOne selected">
    <%= render partial: 'common/main_people_pages/parents', locals: { :is_editable => is_editable, :parents => parents } %>
  </div>

  <div id="accordionTwo" class="accordionLabel"><span class="icon-arrow-right left" style="display: inline-block; margin: 3px 5px 0 0;"></span> Padrinhos</div>
  <div class="accordionLabelContainer accordionTwo">
    <!-- Abas dos padrinhos -->
    <div class="tabContainer">
      <!-- Labels -->
      <div id="tabOne" class="tabLabel selected">Adriano</div>
      <div id="tabTwo" class="tabLabel">Ana Claudia</div>
      <div id="tabThree" class="tabLabel">Carlos</div>
      <div id="tabFour" class="tabLabel">Cleiton</div>
      <div id="tabFive" class="tabLabel">Diogo</div>
      <div id="tabSix" class="tabLabel">Isabel</div>
      <div id="tabSeven" class="tabLabel">Isadora e Edinaldo</div>
      <div id="tabEight" class="tabLabel">Isis</div>
      <div id="tabNine" class="tabLabel">Janaina e Almi</div>
      <div id="tabTen" class="tabLabel">Maiara</div>
      <div id="tabEleven" class="tabLabel">Maria</div>
      <div id="tabTwelve" class="tabLabel">Murilo</div>
      <div id="tabThirteen" class="tabLabel">Padre Milton</div>
      <div id="tabFourteen" class="tabLabel">Rahira</div>

      <!-- Labels containers -->
      <div class="tabLabelContainer tabOne clearfix selected">
        <%= render partial: 'common/main_people_pages/godparents', locals: { :is_editable => is_editable, :slide_id => 3, :current_person => 'adriano', :current_hist => @adriano_hist, :editable_obj => godparents_list ? godparents_list[:adriano_hist] : nil } %>
      </div>
      <div class="tabLabelContainer tabTwo clearfix">
        <%= render partial: 'common/main_people_pages/godparents', locals: { :is_editable => is_editable, :slide_id => 5, :current_person => 'ana-claudia', :current_hist => @ana_claudia_hist, :editable_obj => godparents_list ? godparents_list[:ana_claudia_hist] : nil } %>
      </div>
      <div class="tabLabelContainer tabThree">
          <%= render partial: 'common/main_people_pages/godparents', locals: { :is_editable => is_editable, :slide_id => 7, :current_person => 'carlos', :current_hist => @carlos_hist, :editable_obj => godparents_list ? godparents_list[:carlos_hist] : nil } %>
      </div>
      <div class="tabLabelContainer tabFour">
          <%= render partial: 'common/main_people_pages/godparents', locals: { :is_editable => is_editable, :slide_id => 9, :current_person => 'cleiton', :current_hist => @cleiton_hist, :editable_obj => godparents_list ? godparents_list[:cleiton_hist] : nil } %>
      </div>
      <div class="tabLabelContainer tabFive">
          <%= render partial: 'common/main_people_pages/godparents', locals: { :is_editable => is_editable, :slide_id => 11, :current_person => 'diogo', :current_hist => @diogo_hist, :editable_obj => godparents_list ? godparents_list[:diogo_hist] : nil, :three => true } %>
      </div>
      <div class="tabLabelContainer tabSix">
          <%= render partial: 'common/main_people_pages/godparents', locals: { :is_editable => is_editable, :slide_id => 14, :current_person => 'isabel', :current_hist => @isabel_hist, :editable_obj => godparents_list ? godparents_list[:isabel_hist] : nil } %>
      </div>
      <div class="tabLabelContainer tabSeven">
          <%= render partial: 'common/main_people_pages/godparents', locals: { :is_editable => is_editable, :slide_id => 16, :current_person => 'isa-edi', :current_hist => @isa_edi_hist, :editable_obj => godparents_list ? godparents_list[:isa_edi_hist] : nil } %>
      </div>
      <div class="tabLabelContainer tabEight">
          <%= render partial: 'common/main_people_pages/godparents', locals: { :is_editable => is_editable, :slide_id => 18, :current_person => 'isis', :current_hist => @isis_hist, :editable_obj => godparents_list ? godparents_list[:isis_hist] : nil, :three => true } %>
      </div>
      <div class="tabLabelContainer tabNine">
          <%= render partial: 'common/main_people_pages/godparents', locals: { :is_editable => is_editable, :slide_id => 21, :current_person => 'jana-al', :current_hist => @jana_al_hist, :editable_obj => godparents_list ? godparents_list[:jana_al_hist] : nil } %>
      </div>
      <div class="tabLabelContainer tabTen">
          <%= render partial: 'common/main_people_pages/godparents', locals: { :is_editable => is_editable, :slide_id => 23, :current_person => 'maiara', :current_hist => @maiara_hist, :editable_obj => godparents_list ? godparents_list[:maiara_hist] : nil } %>
      </div>
      <div class="tabLabelContainer tabEleven">
          <%= render partial: 'common/main_people_pages/godparents', locals: { :is_editable => is_editable, :slide_id => 25, :current_person => 'maria', :current_hist => @maria_hist, :editable_obj => godparents_list ? godparents_list[:maria_hist] : nil } %>
      </div>
      <div class="tabLabelContainer tabTwelve">
          <%= render partial: 'common/main_people_pages/godparents', locals: { :is_editable => is_editable, :slide_id => 27, :current_person => 'murilo', :current_hist => @murilo_hist, :editable_obj => godparents_list ? godparents_list[:murilo_hist] : nil } %>
      </div>
      <div class="tabLabelContainer tabThirteen">
          <%= render partial: 'common/main_people_pages/godparents', locals: { :is_editable => is_editable, :slide_id => 29, :current_person => 'pe-milton', :current_hist => @pe_milton_hist, :editable_obj => godparents_list ? godparents_list[:pe_milton_hist] : nil } %>
      </div>
      <div class="tabLabelContainer tabFourteen">
          <%= render partial: 'common/main_people_pages/godparents', locals: { :is_editable => is_editable, :slide_id => 31, :current_person => 'rahira', :current_hist => @rahira_hist, :editable_obj => godparents_list ? godparents_list[:rahira_hist] : nil } %>
      </div>
    </div>
  </div>

  <div id="accordionThree" class="accordionLabel"><span class="icon-arrow-right left" style="display: inline-block; margin: 3px 5px 0 0;"></span> As crianças</div>
  <div class="accordionLabelContainer accordionThree">
    <!--<div style="width: 100%;">-->
      <!--<div style="width: 125px; margin: 0 auto;"><img src="http://webspace.webring.com/people/ea/animetoygirl/under_construction_gifs/Jackhammer.gif" width="125px" height="125px" /></div>-->
      <!--<p style="width: 100%; text-align: center;">Esta área estará disponível em breve!</p>-->
    <!--</div>-->
    <!-- Abas das crianças -->
    <div class="tabContainer">
      <!-- Labels -->
      <div id="tabFifteen" class="tabLabel selected">Antônio</div>
      <div id="tabSixteen" class="tabLabel">Maria Luiza</div>
      <div id="tabSeventeen" class="tabLabel">Mateus, Lucas e Davi</div>
      <div id="tabEighteen" class="tabLabel">Rachel</div>

      <!-- Labels containers -->
      <div class="tabLabelContainer tabFifteen clearfix selected">
        <%= render partial: 'common/main_people_pages/godparents', locals: { :is_editable => is_editable, :slide_id => 33, :current_person => 'antonio', :current_hist => @antonio_hist, :editable_obj => godparents_list ? godparents_list[:antonio_hist] : nil } %>
      </div>
      <div class="tabLabelContainer tabSixteen clearfix">
        <%= render partial: 'common/main_people_pages/godparents', locals: { :is_editable => is_editable, :slide_id => 35, :current_person => 'maria-luiza', :current_hist => @maria_luiza_hist, :editable_obj => godparents_list ? godparents_list[:maria_luiza_hist] : nil } %>
      </div>
      <div class="tabLabelContainer tabSeventeen clearfix">
        <%= render partial: 'common/main_people_pages/godparents', locals: { :is_editable => is_editable, :slide_id => 37, :current_person => 'sobrinhos', :current_hist => @sobrinhos_hist, :editable_obj => godparents_list ? godparents_list[:sobrinhos_hist] : nil, :three => true, :nephews => true } %>
      </div>
      <div class="tabLabelContainer tabEighteen clearfix">
        <%= render partial: 'common/main_people_pages/godparents', locals: { :is_editable => is_editable, :slide_id => 43, :current_person => 'raquel', :current_hist => @raquel_hist, :editable_obj => godparents_list ? godparents_list[:raquel_hist] : nil, :three => true } %>
      </div>
    </div>
  </div>
</div>