config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  get 'manager/index'
  get 'manager/guests'

  resources :guests
  resources :sessions, only: [:new, :create, :destroy, :index]

  #get 'static_page/index'
  get '/cerimonia'        =>  'static_page#ceremony',       :as =>  :ceremony
  get '/listaPresentes'   =>  'static_page#gift_list',      :as =>  :gift_list
  get '/depoimentos'      =>  'static_page#testimonials',   :as =>  :testimonials
  get '/historiaCasal'    =>  'static_page#couple_history', :as =>  :couple_history
  get '/fornecedores'     =>  'static_page#suppliers',      :as =>  :suppliers
  get '/pessoasEspeciais' =>  'static_page#main_people',    :as =>  :main_people
  get '/gerenciamento'    =>  'manager#index',              :as =>  :manager

  match '/savarDepoimentos'       =>  'static_page#create_testimonial',       via: 'post',          :as =>  :save_testimonials
  match '/acesso'                 =>  'sessions#new',                         via:  'get',          :as =>  :login
  match '/upload'                 =>  'manager#guests',                       via:  'post',         :as =>  :upload
  match '/textoNossaHistoria'     =>  'manager#save_couple_history_content',  via:  %w(PATCH post), :as =>  :save_couple_history_content
  # match '/textoNossasPais'        =>  'manager#save_parents_history_content', via:  %w(PATCH post), :as =>  :save_main_people_content
  match '/textoNossasPais'        =>  'manager#save_main_people_content',     via:  %w(PATCH post), :as =>  :save_main_people_content
  match '/sair'                   =>  'sessions#destroy',                     via:  'delete',       :as =>  :signout
  # match '/confirmar'              =>  'guests#confirm',                       via:  %w(get post),   :as =>  :confirmation
  match '/guestAutocompleteList'  =>  'guests#guest_autocomplete_list',       via:  %w(get post)
  match '/selectGuest'            =>  'guests#select_guest',                  via:  %w(get post)
  match '/confirmThisGuest'       =>  'guests#confirm_this_guest',            via:  'post'

  root 'static_page#index'
end

app/views/layouts/_application_footer.html.erb
<footer id="page-footer">
  <p id="copyright" class="left">© 2014 - Developed by Diogo de Lima</p>
  <%= link_to "<span class='icon-cog'></span>".html_safe, manager_path, :class => 'right' %>
</footer>

app/views/layouts/_application_header.html.erb
<header id="page-header" class="clearfix">
    <div id="header-content">
        <nav id="page-menu">
          <!-- TODO: Links do menu de navegação -->
          <%= render 'layouts/navigation_bar' %>
        </nav>
    </div>
</header>

<script>
    $('.locked').click(function(){
        alert('A confirmação de presença já foi encerrada.');
        return false;
    })
</script>

app/views/layouts/_navigation_bar.html.erb
<ul id="main-menu" class="right">
  <li><%= link_to "<span class='icon-home'></span>".html_safe, root_path %></li>
  <li><%= link_to 'Nossa história', couple_history_path %></li>
  <li><%= link_to 'Depoimentos', testimonials_path %></li>
  <li><%= link_to 'Lista de presentes', gift_list_path %></li>
  <li><%= link_to 'Pessoas especiais', main_people_path %></li>
  <!--<li><%#= link_to 'Confirmar presença', confirmation_path %></li>-->
  <li><%= link_to 'Confirmar presença', '#', :class => 'locked' %></li>
  <li><%= link_to 'Cerimônia', ceremony_path %></li>
  <li><%= link_to 'Fornecedores', suppliers_path %></li>
  <% if logged_in? %>
    <li><%= link_to "<span class='icon-exit'></span>".html_safe, signout_path, method: 'delete', :class => 'leave_btn' %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>♥ Felipe & Isaclaudia ♥</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Ubuntu:400,500" type="text/css">
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Rouge+Script" type="text/css">
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= favicon_link_tag image_url('favicon.ico') %>
    <%= csrf_meta_tags %>
  </head>
  <body class="background" data-img-width="1920" data-img-height="1080">
    <div id="page-wrap">
      <!-- header -->
      <%= render 'layouts/application_header' %>
      <!-- /header -->

      <div id="page-content">
        <%#= render 'layouts/side_bar_menu' %>
        <%= yield %>
      </div>

      <!-- footer -->
      <%= render 'layouts/application_footer' %>
      <!-- /footer -->
    </div>
  </body>
</html>